{
 "title": "Web Vitals",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FID values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "fid_metric_score_bucket" }
   ]
  },
  {
   "title": "LCP values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "lcp_metric_score_bucket" }
   ]
  },
  {
   "title": "CLS values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "cls_metric_score_bucket" }
   ]
  }
 ]
}