groups:
  - name: web-vitals
    rules:
      - alert: HighFIDMetric
        expr: quantity_high_fid > 0
        for: 1s
        labels:
          severity: warning
        annotations:
          summary: High FID metric for pokemon website
          description: FID metric is above one, what is bad. Check https://github.com/GoogleChrome/web-vitals#metricratingthresholds to more information
      - alert: HighLCPMetric
        expr: quantity_high_lcp > 0
        for: 1s
        labels:
          severity: warning
        annotations:
          summary: High LCP metric for pokemon website
          description: LCP metric is above one, what is bad. Check https://github.com/GoogleChrome/web-vitals#metricratingthresholds to more information
      - alert: HighCLSMetric
        expr: quantity_high_cls > 0
        for: 1s
        labels:
          severity: warning
        annotations:
          summary: High CLS metric for pokemon website
          description: CLS metric is above one, what is bad. Check https://github.com/GoogleChrome/web-vitals#metricratingthresholds to more information
