version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-network
  node-app:
    image: node:20
    container_name: node-app
    working_dir: /app/backend
    volumes:
      - ../backend:/app/backend
      - /app/backend/node_modules/
    command: bash -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    networks:
      - monitoring-network
  vue-app:
    image: node:20
    container_name: vue-app
    working_dir: /app/frontend
    volumes:
      - ../frontend:/app/frontend
    command: bash -c "npm install && npm run dev --host 0.0.0.0"
    ports:
      - "5175:5175"
    networks:
      - monitoring-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries"
    networks:
      - monitoring-network
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    depends_on:
      - prometheus
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge
