version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  node-app:
    image: node:20
    container_name: node-app
    working_dir: /app/backend
    volumes:
      - ../backend:/app/backend
      - /app/backend/node_modules/
    command: bash -c "npm install && npm run dev"
    ports:
      - "3001:3001"
  vue-app:
    image: node:20
    container_name: vue-app
    working_dir: /app/frontend
    volumes:
      - ../frontend:/app/frontend
    command: bash -c "npm install && npm run dev --host 0.0.0.0"
    ports:
      - "5175:5175"
