global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-metrics"
    static_configs:
      - targets: ["node-app:3001"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

rule_files:
  - "./alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
